version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: courses_manager
      POSTGRES_PASSWORD: courses_manager
      # POSTGRES_DB: courses_manager_pg
    volumes:
      - pg_volume:/var/lib/postgresql/data
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge

volumes:
  pg_volume: {}
