version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: courses_manager
      POSTGRES_PASSWORD: courses_manager
      POSTGRES_HOST_AUTH_METHOD: trust
      # POSTGRES_DB: courses_manager_pg
    volumes:
      - pg_volume:/var/lib/postgresql/data
    networks:
      - default_network
  redis:
    image: 'redis:7.2.1'
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - default

networks:
  default_network:
    driver: bridge

volumes:
  pg_volume: {}
