---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/courses":
    get:
      summary: list courses
      responses:
        '200':
          description: successful
    post:
      summary: create course
      responses:
        '200':
          description: successful
  "/api/v1/courses/{course_id}":
    parameters:
    - name: course_id
      in: path
      description: course_id
      required: true
      schema:
        type: string
    get:
      summary: show course
      responses:
        '200':
          description: successful
    patch:
      summary: update course
      responses:
        '200':
          description: successful
    delete:
      summary: delete course
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
